"""initial schema - products, machine_states, defects

Revision ID: ebbb2c3e363a
Revises: 
Create Date: 2025-11-29 02:47:55.074722+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ebbb2c3e363a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('version', sa.String(length=10), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('molding_machine_id', sa.String(length=50), nullable=False),
    sa.Column('overall_reject', sa.Boolean(), nullable=False),
    sa.Column('defect_count', sa.Integer(), nullable=False),
    sa.Column('total_severity_score', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_products_machine_timestamp', 'products', ['molding_machine_id', 'timestamp'], unique=False)
    op.create_index('idx_products_reject_timestamp', 'products', ['overall_reject', 'timestamp'], unique=False)
    op.create_index(op.f('ix_products_molding_machine_id'), 'products', ['molding_machine_id'], unique=False)
    op.create_index(op.f('ix_products_overall_reject'), 'products', ['overall_reject'], unique=False)
    op.create_index(op.f('ix_products_timestamp'), 'products', ['timestamp'], unique=False)
    op.create_index(op.f('ix_products_version'), 'products', ['version'], unique=False)
    op.create_table('defects',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('product_id', sa.BigInteger(), nullable=False),
    sa.Column('defect_type', sa.String(length=50), nullable=False),
    sa.Column('reject', sa.Boolean(), nullable=False),
    sa.Column('pixel_severity_value', sa.Numeric(precision=10, scale=6), nullable=True, comment='Pixel severity score (0.0 to 1.0)'),
    sa.Column('pixel_severity_reject', sa.Boolean(), nullable=True, comment='Whether pixel severity exceeded threshold'),
    sa.Column('threshold', sa.Numeric(precision=10, scale=6), nullable=True, comment='Threshold value used for rejection decision'),
    sa.Column('min_value', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('max_value', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_defects_product_type', 'defects', ['product_id', 'defect_type'], unique=False)
    op.create_index('idx_defects_severity', 'defects', ['pixel_severity_value'], unique=False)
    op.create_index('idx_defects_type_reject', 'defects', ['defect_type', 'reject'], unique=False)
    op.create_index(op.f('ix_defects_defect_type'), 'defects', ['defect_type'], unique=False)
    op.create_index(op.f('ix_defects_product_id'), 'defects', ['product_id'], unique=False)
    op.create_index(op.f('ix_defects_reject'), 'defects', ['reject'], unique=False)
    op.create_table('machine_states',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('product_id', sa.BigInteger(), nullable=False),
    sa.Column('cycle_time', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('vtop_time', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('charge_time', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('cool_time_sp', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('inj_time_sp', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('clamp_open_time_cv', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('clamp_close_time_cv', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('ej_fwd_time_cv', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('ej_ret_time_cv', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('vp_transfer_time_sp', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('hold_segment_1_time_sp', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('hold_segment_2_time_sp', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('hold_segment_3_time_sp', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('hold_segment_4_time_sp', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('inj_peak_pressure', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('fill_peak_press', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('vtop_press', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('hold_segment_1_pressure_sp', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('hold_segment_2_pressure_sp', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('hold_segment_3_pressure_sp', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('hold_segment_4_pressure_sp', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('hold_segment_5_pressure_sp', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('fill_segment_1_pressure_sp', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('fill_segment_2_pressure_sp', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('fill_segment_3_pressure_sp', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('fill_segment_4_pressure_sp', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('fill_segment_5_pressure_sp', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('clamp_force_sp', sa.BigInteger(), nullable=True),
    sa.Column('tonnage_force_cv', sa.BigInteger(), nullable=True),
    sa.Column('barrel_1', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('barrel_2', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('barrel_3', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('barrel_4', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('barrel_5', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('barrel_6', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('barrel_n1', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('barrel_n2', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('h1_temp_sp', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('h2_temp_sp', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('h3_temp_sp', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('h4_temp_sp', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('h5_temp_sp', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('h6_temp_sp', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('n1_temp_sp', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('n2_temp_sp', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('inj_start_pos', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('vtop_pos', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('vp_transfer_position_sp', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('cushion_min', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('cushion_fin', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('fill_segment_1_sp', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('fill_segment_2_sp', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('fill_segment_3_sp', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('fill_segment_4_sp', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('fill_segment_5_sp', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('fill_segment_xfer_1_to_2_sp', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('fill_segment_xfer_2_to_3_sp', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('fill_segment_xfer_3_to_4_sp', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('fill_segment_xfer_4_to_5_sp', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('shot_count', sa.Integer(), nullable=True),
    sa.Column('shot_size_sp', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('pull_back_before_sp', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('pull_back_after_sp', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('buzzer_alarm', sa.Boolean(), nullable=True),
    sa.Column('alarm_led', sa.Boolean(), nullable=True),
    sa.Column('cycle_stop_fault', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_machine_states_barrel_temps', 'machine_states', ['barrel_1', 'barrel_2', 'barrel_3'], unique=False)
    op.create_index('idx_machine_states_cycle_time', 'machine_states', ['cycle_time'], unique=False)
    op.create_index('idx_machine_states_shot_count', 'machine_states', ['shot_count'], unique=False)
    op.create_index(op.f('ix_machine_states_product_id'), 'machine_states', ['product_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_machine_states_product_id'), table_name='machine_states')
    op.drop_index('idx_machine_states_shot_count', table_name='machine_states')
    op.drop_index('idx_machine_states_cycle_time', table_name='machine_states')
    op.drop_index('idx_machine_states_barrel_temps', table_name='machine_states')
    op.drop_table('machine_states')
    op.drop_index(op.f('ix_defects_reject'), table_name='defects')
    op.drop_index(op.f('ix_defects_product_id'), table_name='defects')
    op.drop_index(op.f('ix_defects_defect_type'), table_name='defects')
    op.drop_index('idx_defects_type_reject', table_name='defects')
    op.drop_index('idx_defects_severity', table_name='defects')
    op.drop_index('idx_defects_product_type', table_name='defects')
    op.drop_table('defects')
    op.drop_index(op.f('ix_products_version'), table_name='products')
    op.drop_index(op.f('ix_products_timestamp'), table_name='products')
    op.drop_index(op.f('ix_products_overall_reject'), table_name='products')
    op.drop_index(op.f('ix_products_molding_machine_id'), table_name='products')
    op.drop_index('idx_products_reject_timestamp', table_name='products')
    op.drop_index('idx_products_machine_timestamp', table_name='products')
    op.drop_table('products')
    # ### end Alembic commands ###